apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: jx-staging
spec:
  encryptedData:
    foo: AgAFa46cpToZw8x8mEo1WXsf7sS7DW1Y7yNJZjjUaIJr1rsxENupf4Yvq9InSfFZefRrO7UYOZPFkg46WmWAzy1iFS6MQVNxwydk9YCgkpt+21HsptWXjT42wfefHTf6VOLTS0sHMJHDmAkF2wgGQShWoQ1HUrpRbuTsSIresBLObBH/YtEOihur85ppbu5qIJxTKMjPKUyPyXPwgZHWBxioKPfoFge8f3dzFoWRHEnmBVPEh4twqn0D/1h8FLzHBiVsh/p4tsjZx6Ur62dU3SjVH61HWKhMN//VmdwWFkeUBZ6CWq9PK2/jltr3OenHLxGvZV7jLfJYlu397Xuz0O1teM1bCM49rebkICJ64ArFGWBM9lXS7ny/5Pfw6nd6v2KNdxKfHu0kp5S/hRlv5lPN7facy7k+4vmM+BmTBaPY3uD3luJwu8lUO3TpjXicfiW142Kp86rXoKfs5g4HIbYd37S4ehpX4AZHnKvYy/J+P18qUUueeUKToaqklAExpvzXz/7pR82VhbMwXGGfZ+0dJsZhJMgB1s1HkJ/sq2Q1Lc1KyqPLatA/YxulwHA2WHL5yObqsJQjc12k58rE780mjLUQoWOqD09GaK8S4z55F84U0of5GF+Ij9KtMA0ck0DGashgiAjdzjugPdvOqUDK76+VaUrO83Sxs9Y9OUcv/sp8j6KTQOI2fca3EfLCttICYsA=

